spring:
  application:
    name: task.1-2
  datasource:
    url: jdbc:mysql://localhost:3306/task-12?useUnicode=true&characterEncoding=UTF-8
    username: ${DB_USER:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
jwt:
  secret: ${DB_SecretKey}